### ISSUE TITLE
Telerik Library Required?

### ISSUE THREAD

**Issue by jconaty** [jsturtevant/UnconsciousBias#3]
I cannot compile :(

**Comment by jsturtevant** [comment]
You can sign up for a trial at http://www.telerik.com/universal-windows-platform-ui and download the toolkit.  

Delete the old reference and add the new one. Then rebuild.

![image](https://cloud.githubusercontent.com/assets/648372/22989180/e0d2f6ec-f382-11e6-80dd-759428c23219.png)
